server:
    port: 8092 #启动端口

spring:
    jmx:
      default-domain: BaseServer
    application:
      name: base
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:2297/1121?useUnicode=true&amp;characterEncoding=UTF-8&amp;TreatTinyAsBoolean=false&amp;autoReconnect=true&amp;rewriteBatchedStatements=TRUE&amp;failOverReadOnly=false&amp;autoReconnect=true
      username: root
      password:
      #url: jdbc:mysql://123.57.140.180:3306/intestinal_cancer_sys?useUnicode=true&amp;characterEncoding=UTF-8&amp;TreatTinyAsBoolean=false&amp;autoReconnect=true&amp;rewriteBatchedStatements=TRUE&amp;failOverReadOnly=false&amp;autoReconnect=true
      #username: root
      #password: kaifa180mysqlroot
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat,wall,log4j
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.showSqlMillis=5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from druid
      testWhileIdle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnBorrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    redis:
        hostName: 192.168.1.8
        port: 6379
        password:
        timeout: 2000
        database: 9
    pool:
          max-active: 8
          min-idle: 0
          max-idle: 8
          max-wait: 10000
    http:
      multipart:
        maxFileSize: 100MB # 设置单个文件的最大长度
        maxRequestSize: 100MB # 设置最大的请求文件的大小
http:
    maxTotal: 100
    defaultMaxPerRoute: 20
    connectTimeout: 1000
    connectionRequestTimeout: 500
    socketTimeout: 10000
    staleConnectionCheckEnabled: true
login:
  authCode:
    codeTime: 180   #短信验证码失效时间 线上3分钟

sms:
  accountSid: 8a216da862cc8f910162d8fb7e440967
  authToken: 59d7166ee80c44368675125b0c0ff874
  serverIp: app.cloopen.com
  serverPort: 8883
  appId: 8a216da862dcd1050162dda6561c00e3

eureka:
     client:
        serviceUrl:
          defaultZone: http://localhost:8090/eureka
logging:
  config:
    classpath: log4j2.xml

prop:
  upload-folder: /Users/zongtong/Desktop/img
  upload-folder-dna: /dna/result
  upload-folder-img: /fit/img
  upload-folder-img-chang-result: /chang/result
  upload-folder-file-cancer-result: /cancer/result

execl:
  styleName:
  isMergedRegion: false

ytx:
  base:
    bi:
      token:
        biexpire: 20 #20秒 token过期时间 单位秒
      path: http://192.168.1.16:50651/api/v1/login/receiveToken
      timeout: 5000
      readTimeout: 5000

sftp:
  url:
    path: pick
    name: pick
    ip: 219.234.82.87
    port: 5522
